<?php

namespace App\Notifications\Admissions;

use App\Contracts\SchoolAwareMailNotification;
use App\Models\Admissions\AdmissionApplication;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

abstract class BaseAdmissionNotification extends Notification implements SchoolAwareMailNotification
{
    use Queueable;

    public function __construct(
        public AdmissionApplication $application,
        public ?string $message = null
    ) {}

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function schoolIdForMail(object $notifiable): ?int
    {
        return filled($this->application->school_id) ? (int) $this->application->school_id : null;
    }

    protected function mail(string $subject, string $headline): MailMessage
    {
        $mail = (new MailMessage)
            ->subject($subject)
            ->greeting('Hello,')
            ->line($headline)
            ->line('Application number: '.$this->application->application_number);

        if (filled($this->message)) {
            $mail->line($this->message);
        }

        return $mail
            ->action('Track Application', route('admissions.track'))
            ->line('This message was generated by the school admission portal.');
    }
}
