<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-xl font-semibold leading-tight text-gray-900">
                    Scratch Card Request
                </h2>
                <p class="mt-1 text-sm text-gray-500">
                    {{ $batch->title ?? 'Request #' . $batch->id }} from {{ $batch->school->name ?? 'N/A' }}.
                </p>
            </div>

            @if ($batch->status === 'generated' && $batch->cards_count > 0)
                <a href="{{ route('admin.scratch-card-requests.download', $batch) }}"
                   class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700">
                    Download CSV
                </a>
            @endif
        </div>
    </x-slot>

    <div class="py-8">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            @if (session('success'))
                <div class="mb-6 rounded-xl bg-green-50 p-4 text-sm text-green-700">
                    {{ session('success') }}
                </div>
            @endif

            @if (session('error'))
                <div class="mb-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">
                    {{ session('error') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="mb-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">
                    <p class="font-medium">Please fix the highlighted fields.</p>
                </div>
            @endif

            <div class="mb-6 grid gap-6 lg:grid-cols-4">
                <div class="rounded-2xl bg-white p-6 shadow-sm">
                    <p class="text-sm font-medium text-gray-500">Request Status</p>
                    <p class="mt-3 text-lg font-semibold text-gray-900">
                        {{ ucfirst(str_replace('_', ' ', $batch->status)) }}
                    </p>
                </div>

                <div class="rounded-2xl bg-white p-6 shadow-sm">
                    <p class="text-sm font-medium text-gray-500">Payment</p>
                    <p class="mt-3 text-lg font-semibold text-gray-900">
                        {{ ucfirst(str_replace('_', ' ', $batch->payment_status)) }}
                    </p>
                    <p class="mt-1 text-sm text-gray-500">
                        {{ $batch->currency }} {{ number_format($batch->amount, 2) }}
                    </p>
                </div>

                <div class="rounded-2xl bg-white p-6 shadow-sm">
                    <p class="text-sm font-medium text-gray-500">Cards</p>
                    <p class="mt-3 text-lg font-semibold text-gray-900">
                        {{ $batch->cards_count }} / {{ $batch->quantity }}
                    </p>
                    <p class="mt-1 text-sm text-gray-500">
                        {{ $batch->unused_cards_count }} unused, {{ $batch->used_cards_count }} used
                    </p>
                </div>

                <div class="rounded-2xl bg-white p-6 shadow-sm">
                    <p class="text-sm font-medium text-gray-500">Generated By</p>
                    <p class="mt-3 text-lg font-semibold text-gray-900">
                        {{ $batch->generatedBy->name ?? 'Not generated' }}
                    </p>
                </div>
            </div>

            <div class="mb-6 rounded-2xl bg-white p-6 shadow-sm">
                <h3 class="text-base font-semibold text-gray-900">Request Details</h3>

                <dl class="mt-4 grid gap-4 text-sm text-gray-600 sm:grid-cols-2 lg:grid-cols-4">
                    <div>
                        <dt class="font-medium text-gray-500">School</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->school->name ?? 'N/A' }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Class</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->schoolClass->name ?? 'All Classes' }} {{ $batch->schoolClass->section ?? '' }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Academic Session</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->academicSession->name ?? 'N/A' }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Term</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->term->name ?? 'N/A' }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Result Type</dt>
                        <dd class="mt-1 text-gray-900">{{ ucfirst(str_replace('_', ' ', $batch->result_type)) }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Quantity</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->quantity }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Payment Method</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->payment_method ? ucfirst(str_replace('_', ' ', $batch->payment_method)) : 'No method' }}</dd>
                    </div>
                    <div>
                        <dt class="font-medium text-gray-500">Payment Reference</dt>
                        <dd class="mt-1 text-gray-900">{{ $batch->payment_reference ?: 'N/A' }}</dd>
                    </div>
                </dl>

                @if ($batch->payment_confirmed_at)
                    <div class="mt-6 border-t border-gray-100 pt-4 text-sm text-gray-600">
                        Confirmed by {{ $batch->paymentConfirmedBy->name ?? 'N/A' }}
                        on {{ $batch->payment_confirmed_at->format('d M Y, h:i A') }}.
                    </div>
                @endif

                @if (data_get($batch->metadata, 'request_note'))
                    <div class="mt-6 border-t border-gray-100 pt-4">
                        <p class="text-sm font-medium text-gray-500">Request Note</p>
                        <p class="mt-1 text-sm text-gray-900">{{ data_get($batch->metadata, 'request_note') }}</p>
                    </div>
                @endif
            </div>

            @if ($batch->status !== 'revoked')
                <div class="mb-6 grid gap-6 lg:grid-cols-2">
                    <div class="rounded-2xl bg-white p-6 shadow-sm">
                        <h3 class="text-base font-semibold text-gray-900">Confirm Payment</h3>
                        <p class="mt-1 text-sm text-gray-500">
                            Mark manual payment as paid before card generation.
                        </p>

                        <form method="POST"
                              action="{{ route('admin.scratch-card-requests.confirm-payment', $batch) }}"
                              class="mt-4 space-y-4">
                            @csrf

                            <div class="grid gap-4 sm:grid-cols-2">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Amount</label>
                                    <input type="number"
                                           name="amount"
                                           min="0"
                                           step="0.01"
                                           value="{{ old('amount', $batch->amount) }}"
                                           class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">
                                    @error('amount')
                                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                                    @enderror
                                </div>

                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Currency</label>
                                    <input type="text"
                                           name="currency"
                                           value="{{ old('currency', $batch->currency) }}"
                                           class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">
                                    @error('currency')
                                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>

                            <div class="grid gap-4 sm:grid-cols-2">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Payment Method</label>
                                    <select name="payment_method"
                                            class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">
                                        <option value="bank_transfer" @selected(old('payment_method', $batch->payment_method) === 'bank_transfer')>Bank Transfer</option>
                                        <option value="cash" @selected(old('payment_method', $batch->payment_method) === 'cash')>Cash</option>
                                        <option value="manual" @selected(old('payment_method', $batch->payment_method) === 'manual')>Manual</option>
                                    </select>
                                    @error('payment_method')
                                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                                    @enderror
                                </div>

                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Payment Reference</label>
                                    <input type="text"
                                           name="payment_reference"
                                           value="{{ old('payment_reference', $batch->payment_reference) }}"
                                           class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">
                                    @error('payment_reference')
                                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>

                            <div class="flex justify-end">
                                <button type="submit"
                                        class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700">
                                    Confirm Payment
                                </button>
                            </div>
                        </form>
                    </div>

                    <div class="rounded-2xl bg-white p-6 shadow-sm">
                        <h3 class="text-base font-semibold text-gray-900">Generate Cards</h3>
                        <p class="mt-1 text-sm text-gray-500">
                            Generation uses the requested quantity and cannot be repeated for this batch.
                        </p>

                        @if ($batch->cards_count > 0)
                            <div class="mt-4 rounded-xl bg-gray-50 p-4 text-sm text-gray-600">
                                This request already has generated cards.
                            </div>
                        @elseif ($batch->payment_status !== 'paid' || ! $batch->payment_confirmed_at)
                            <div class="mt-4 rounded-xl bg-yellow-50 p-4 text-sm text-yellow-700">
                                Confirm payment before generating cards.
                            </div>
                        @else
                            <form method="POST"
                                  action="{{ route('admin.scratch-card-requests.generate', $batch) }}"
                                  class="mt-4 space-y-4">
                                @csrf

                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Max Uses Per Card</label>
                                    <input type="number"
                                           name="max_uses"
                                           min="1"
                                           max="100"
                                           value="{{ old('max_uses', 1) }}"
                                           class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">
                                    @error('max_uses')
                                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                                    @enderror
                                </div>

                                <div class="flex justify-end">
                                    <button type="submit"
                                            class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700">
                                        Generate {{ $batch->quantity }} Cards
                                    </button>
                                </div>
                            </form>
                        @endif
                    </div>
                </div>

                <div class="mb-6 rounded-2xl bg-white p-6 shadow-sm">
                    <h3 class="text-base font-semibold text-gray-900">Revoke Batch</h3>
                    <p class="mt-1 text-sm text-gray-500">
                        Revoking a batch marks the request and all generated cards as revoked.
                    </p>

                    <form method="POST"
                          action="{{ route('admin.scratch-card-requests.revoke', $batch) }}"
                          class="mt-4 flex gap-3">
                        @csrf

                        <input type="text"
                               name="revoke_reason"
                               placeholder="Reason for revoking this batch"
                               class="block w-full rounded-xl border-gray-300 shadow-sm focus:border-gray-900 focus:ring-gray-900">

                        <button type="submit"
                                class="rounded-xl border border-red-300 px-4 py-2 text-sm font-medium text-red-700 hover:bg-red-50">
                            Revoke Batch
                        </button>
                    </form>

                    @error('revoke_reason')
                        <p class="mt-2 text-sm text-red-600">{{ $message }}</p>
                    @enderror
                </div>
            @endif

            <div class="overflow-hidden rounded-2xl bg-white shadow-sm">
                <div class="border-b border-gray-100 px-6 py-4">
                    <h3 class="text-base font-semibold text-gray-900">
                        Cards
                    </h3>
                    <p class="mt-1 text-sm text-gray-500">
                        PIN codes are included in the CSV download after generation.
                    </p>
                </div>

                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-100">
                        <thead class="bg-gray-50">
                            <tr>
                                <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Serial</th>
                                <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Usage</th>
                                <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Status</th>
                                <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Used By</th>
                                <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Revocation</th>
                                <th class="px-6 py-3 text-right text-xs font-medium uppercase tracking-wide text-gray-500">Action</th>
                            </tr>
                        </thead>

                        <tbody class="divide-y divide-gray-100 bg-white">
                            @forelse ($cards as $card)
                                <tr>
                                    <td class="px-6 py-4">
                                        <div class="font-medium text-gray-900">
                                            {{ $card->serial_number }}
                                        </div>
                                        <div class="text-sm text-gray-500">
                                            PIN hidden. Use CSV download.
                                        </div>
                                    </td>

                                    <td class="px-6 py-4 text-sm text-gray-600">
                                        {{ $card->used_count }} / {{ $card->max_uses }} uses
                                    </td>

                                    <td class="px-6 py-4">
                                        <span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">
                                            {{ ucfirst($card->status) }}
                                        </span>
                                    </td>

                                    <td class="px-6 py-4 text-sm text-gray-600">
                                        {{ $card->usedByStudent?->fullName() ?? 'Not used' }}
                                    </td>

                                    <td class="px-6 py-4 text-sm text-gray-600">
                                        @if ($card->revoked_at)
                                            {{ $card->revoked_at->format('d M Y, h:i A') }}<br>
                                            {{ $card->revoke_reason }}
                                        @else
                                            Not revoked
                                        @endif
                                    </td>

                                    <td class="px-6 py-4 text-right">
                                        @if ($card->status !== 'revoked')
                                            <form method="POST"
                                                  action="{{ route('admin.scratch-cards.revoke', $card) }}"
                                                  class="flex justify-end gap-2">
                                                @csrf

                                                <input type="text"
                                                       name="revoke_reason"
                                                       placeholder="Reason"
                                                       class="w-48 rounded-xl border-gray-300 text-sm shadow-sm focus:border-gray-900 focus:ring-gray-900">

                                                <button type="submit"
                                                        class="rounded-xl border border-red-300 px-3 py-2 text-xs font-medium text-red-700 hover:bg-red-50">
                                                    Revoke
                                                </button>
                                            </form>
                                        @else
                                            <span class="text-sm text-gray-400">Revoked</span>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="px-6 py-12 text-center">
                                        <p class="text-sm font-medium text-gray-900">No cards generated yet.</p>
                                        <p class="mt-1 text-sm text-gray-500">
                                            Confirm payment, then generate cards from this request.
                                        </p>
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                <div class="border-t border-gray-100 px-6 py-4">
                    {{ $cards->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
