<?php

use App\Services\System\DeploymentModeService;

return [
    /*
    |--------------------------------------------------------------------------
    | Sanfaani Demo Automation Foundation
    |--------------------------------------------------------------------------
    |
    | This configuration powers demo requests, demo sessions, demo credentials,
    | activity tracking, and expiry. It does not implement onboarding,
    | marketing automation sequences, billing, update delivery, backups, or
    | marketplace packaging.
    |
    */

    'enabled' => (bool) env('SANFAANI_DEMO_ENABLED', true),
    'default_duration_days' => (int) env('SANFAANI_DEMO_DEFAULT_DURATION_DAYS', 7),
    'max_active_sessions' => (int) env('SANFAANI_DEMO_MAX_ACTIVE_SESSIONS', 25),
    'reset_enabled' => (bool) env('SANFAANI_DEMO_RESET_ENABLED', false),
    'email_enabled' => (bool) env('SANFAANI_DEMO_EMAIL_ENABLED', true),
    'school_slug_prefix' => 'demo-school',
    'password_length' => 14,
    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin demo',
            'assign_role' => 'school_admin',
            'note' => 'Simulated Super Admin experience scoped to the demo school.',
        ],
        'school_admin' => [
            'label' => 'School Admin demo',
            'assign_role' => 'school_admin',
        ],
        'teacher' => [
            'label' => 'Teacher demo',
            'assign_role' => 'teacher',
        ],
        'parent' => [
            'label' => 'Parent demo',
            'assign_role' => 'parent',
        ],
        'student' => [
            'label' => 'Student demo',
            'assign_role' => 'student',
        ],
        'result_officer' => [
            'label' => 'Result Officer demo',
            'assign_role' => 'result_officer',
        ],
        'accountant' => [
            'label' => 'Accountant demo',
            'assign_role' => 'accountant',
        ],
    ],
    'marketplace' => [
        'enabled' => (bool) env('SANFAANI_MARKETPLACE_DEMO_ENABLED', false),
        'auto_login' => (bool) env('SANFAANI_MARKETPLACE_DEMO_AUTO_LOGIN', false),
        'reset_hours' => (int) env('SANFAANI_MARKETPLACE_DEMO_RESET_HOURS', 24),
        'safe_mode' => (bool) env('SANFAANI_MARKETPLACE_DEMO_SAFE_MODE', true),
        'school' => [
            'name' => '[DEMO] Sanfaani Marketplace Demo School',
            'slug' => 'sanfaani-marketplace-demo',
            'school_code' => 'DEMO-MARKET',
            'email' => 'demo@sanfaani.net',
            'phone' => '+234 800 000 0000',
            'address' => 'Sample Demo Campus, Lagos',
        ],
        'accounts' => [
            'school_admin' => [
                'label' => 'School Admin',
                'assign_role' => 'school_admin',
                'email' => 'schooladmin@demo.sanfaani.net',
                'password' => env('SANFAANI_MARKETPLACE_DEMO_PASSWORD', 'password'),
                'public' => true,
                'dashboard_route' => 'school.dashboard',
                'description' => 'Explore school setup, classes, staff, students, results, and settings with destructive actions blocked.',
            ],
            'teacher' => [
                'label' => 'Teacher',
                'assign_role' => 'teacher',
                'email' => 'teacher@demo.sanfaani.net',
                'password' => env('SANFAANI_MARKETPLACE_DEMO_PASSWORD', 'password'),
                'public' => true,
                'dashboard_route' => 'school.dashboard',
                'description' => 'Explore assigned classes, teacher result entry, CBT, and student visibility.',
            ],
            'result_officer' => [
                'label' => 'Result Officer',
                'assign_role' => 'result_officer',
                'email' => 'resultofficer@demo.sanfaani.net',
                'password' => env('SANFAANI_MARKETPLACE_DEMO_PASSWORD', 'password'),
                'public' => true,
                'dashboard_route' => 'school.dashboard',
                'description' => 'Explore result upload, review, publishing, and result-checking workflows.',
            ],
            'accountant' => [
                'label' => 'Accountant',
                'assign_role' => 'accountant',
                'email' => 'accountant@demo.sanfaani.net',
                'password' => env('SANFAANI_MARKETPLACE_DEMO_PASSWORD', 'password'),
                'public' => false,
                'dashboard_route' => 'profile.edit',
                'description' => 'Seeded as a safe foundation, but not advertised until accountant workflows are dashboard-ready.',
            ],
        ],
        'blocked_routes' => [
            'password.update',
            'verification.send',
            'profile.update',
            'profile.destroy',
            'admin.platform-settings.update',
            'admin.schools.archive',
            'admin.schools.restore',
            'admin.schools.admins.reset-password',
            'admin.schools.admins.send-reset-link',
            'admin.schools.admins.disable',
            'admin.schools.admins.enable',
            'admin.support-access.stop',
            'admin.support-access.revoke',
            'admin.subscription-plans.archive',
            'admin.updates.store',
            'admin.updates.preflight',
            'admin.updates.mark-ready',
            'admin.backups.store',
            'admin.backups.prune',
            'admin.license.store',
            'admin.license.validate',
            'admin.system-maintenance.*',
            'admin.payments.confirm',
            'admin.payment-settings.update',
            'admin.mail-settings.update',
            'admin.mail-settings.test',
            'admin.email-marketing.campaigns.send',
            'admin.email-marketing.automations.run',
            'admin.scratch-card-requests.confirm-payment',
            'admin.scratch-card-requests.generate',
            'admin.scratch-card-requests.revoke',
            'admin.scratch-cards.revoke',
            'school.mail-settings.update',
            'school.mail-settings.test',
            'school.profile.update',
            'school.public-page.update',
            'school.branding.update',
            'school.branding.logo',
            'school.branding.favicon',
            'school.students.destroy',
            'school.students.restore',
            'school.students.elective-subjects.destroy',
            'school.teacher-assignments.archive',
            'school.teacher-assignments.restore',
            'school.sessions.activate',
            'school.sessions.archive',
            'school.sessions.restore',
            'school.terms.activate',
            'school.terms.archive',
            'school.terms.restore',
            'school.results.manual.destroy',
            'school.results.publishing.publish',
            'school.results.publishing.publish-single',
            'school.results.publishing.unpublish',
            'school.results.publishing.unpublish-single',
            'school.result-reviews.void',
            'school.communications.students.send',
            'school.communications.bulk.send',
            'school.communications.bulk.process',
            'school.communications.bulk.retry-failed',
        ],
    ],
    'deployment_modes' => [
        DeploymentModeService::MODE_SAAS,
        DeploymentModeService::MODE_SINGLE_SCHOOL,
        DeploymentModeService::MODE_MANAGED,
    ],
    'license_modes' => [
        DeploymentModeService::LICENSE_SUBSCRIPTION,
        DeploymentModeService::LICENSE_TRIAL,
        DeploymentModeService::LICENSE_DEMO,
    ],
];
