<?php

use App\Services\System\DeploymentModeService;

/*
|--------------------------------------------------------------------------
| Sanfaani Deployment Mode Behavior
|--------------------------------------------------------------------------
|
| This map separates SaaS, single-school, and managed-deployment behavior
| without duplicating feature flags, subscription entitlements, or tenant
| logic. Feature-gated groups reference config/features.php and are resolved
| through FeatureAccessService.
|
*/

return [
    'route_groups' => [
        'platform_dashboard' => ['label' => 'Platform dashboard'],
        'platform_schools' => ['label' => 'School management'],
        'platform_onboarding' => ['label' => 'Central school onboarding'],
        'platform_subscriptions' => ['label' => 'SaaS subscriptions', 'features' => ['saas_billing']],
        'platform_features' => ['label' => 'Feature overrides', 'features' => ['saas_billing']],
        'platform_marketing' => ['label' => 'Marketing automation', 'features' => ['marketing_automation']],
        'platform_demo' => ['label' => 'Demo and trial pipeline', 'features' => ['demo_system']],
        'demo_sessions' => ['label' => 'Demo session management', 'features' => ['demo_system']],
        'guided_onboarding' => ['label' => 'Guided onboarding', 'features' => ['guided_onboarding']],
        'platform_payments' => ['label' => 'Platform payments', 'features' => ['saas_billing']],
        'platform_result_system' => ['label' => 'Platform result system'],
        'platform_scratch_cards' => ['label' => 'Platform scratch-card requests', 'features' => ['scratch_cards']],
        'platform_communications' => ['label' => 'Platform communication tools'],
        'platform_support' => ['label' => 'Platform support tools', 'features' => ['support_tools']],
        'platform_mail' => ['label' => 'Platform mail settings'],
        'platform_settings' => ['label' => 'Platform settings'],
        'platform_security' => ['label' => 'Platform security'],
        'platform_audit' => ['label' => 'Platform audit logs'],
        'local_dashboard' => ['label' => 'Local owner dashboard'],
        'local_school_settings' => ['label' => 'Local school settings'],
        'local_branding' => ['label' => 'Local branding placeholder'],
        'local_mail_settings' => ['label' => 'Local SMTP settings placeholder'],
        'license_activation' => ['label' => 'License activation', 'features' => ['license_activation']],
        'standalone_installer' => ['label' => 'Standalone installer', 'features' => ['standalone_installer'], 'requires_uninstalled' => true],
        'standalone_license' => ['label' => 'License status placeholder', 'features' => ['license_activation']],
        'standalone_updates' => ['label' => 'Standalone update placeholder', 'features' => ['update_manager']],
        'managed_support' => ['label' => 'Managed support tools', 'features' => ['support_tools']],
        'managed_backups' => ['label' => 'Managed backup placeholder', 'features' => ['managed_backups']],
        'managed_updates' => ['label' => 'Managed update placeholder', 'features' => ['update_manager']],
        'managed_white_label' => ['label' => 'Managed white-label placeholder', 'features' => ['white_label_branding']],
        'system_maintenance' => ['label' => 'System maintenance'],
        'system_status' => ['label' => 'System status'],
    ],

    'dashboard_widgets' => [
        'schools_total' => ['label' => 'Schools total', 'route_group' => 'platform_schools'],
        'active_subscriptions' => ['label' => 'Active subscriptions', 'route_group' => 'platform_subscriptions'],
        'demo_requests' => ['label' => 'Demo requests', 'route_group' => 'platform_demo'],
        'lead_pipeline' => ['label' => 'Lead pipeline', 'route_group' => 'platform_onboarding'],
        'scratch_card_requests' => ['label' => 'Scratch card requests', 'route_group' => 'platform_scratch_cards'],
        'platform_payments' => ['label' => 'Platform payments', 'route_group' => 'platform_payments'],
        'local_school_profile' => ['label' => 'Local school profile', 'route_group' => 'local_school_settings'],
        'local_license_status' => ['label' => 'License status', 'route_group' => 'standalone_license'],
        'local_update_status' => ['label' => 'Update status', 'route_group' => 'standalone_updates'],
        'managed_support_status' => ['label' => 'Managed support status', 'route_group' => 'managed_support'],
        'managed_backup_status' => ['label' => 'Managed backup status', 'route_group' => 'managed_backups'],
        'managed_update_status' => ['label' => 'Managed update status', 'route_group' => 'managed_updates'],
        'white_label_status' => ['label' => 'White-label status', 'route_group' => 'managed_white_label'],
        'system_health' => ['label' => 'System health', 'route_group' => 'system_status'],
        'onboarding_progress' => ['label' => 'Onboarding progress', 'route_group' => 'guided_onboarding'],
        'marketing_new_leads' => ['label' => 'New leads', 'route_group' => 'platform_marketing'],
        'marketing_sales_tasks' => ['label' => 'Sales tasks', 'route_group' => 'platform_marketing'],
        'marketing_trial_leads' => ['label' => 'Trial leads', 'route_group' => 'platform_marketing'],
        'marketing_renewals' => ['label' => 'Renewal reminders', 'route_group' => 'platform_marketing'],
        'marketing_conversions' => ['label' => 'Conversion milestones', 'route_group' => 'platform_marketing'],
    ],

    'settings_sections' => [
        'platform' => ['label' => 'Platform settings', 'route_group' => 'platform_settings'],
        'billing' => ['label' => 'Billing settings', 'route_group' => 'platform_subscriptions'],
        'marketing' => ['label' => 'Marketing settings', 'route_group' => 'platform_marketing'],
        'localization' => ['label' => 'Localization settings', 'route_group' => 'platform_settings'],
        'local_school' => ['label' => 'Local school settings', 'route_group' => 'local_school_settings'],
        'local_branding' => ['label' => 'Local branding', 'route_group' => 'local_branding'],
        'local_mail' => ['label' => 'Local SMTP settings', 'route_group' => 'local_mail_settings'],
        'license' => ['label' => 'License status', 'route_group' => 'standalone_license'],
        'updates' => ['label' => 'Updates', 'route_group' => 'standalone_updates'],
        'managed_support' => ['label' => 'Managed support', 'route_group' => 'managed_support'],
        'managed_backups' => ['label' => 'Managed backups', 'route_group' => 'managed_backups'],
        'managed_updates' => ['label' => 'Managed updates', 'route_group' => 'managed_updates'],
        'white_label' => ['label' => 'White-label controls', 'route_group' => 'managed_white_label'],
        'security' => ['label' => 'Security', 'route_group' => 'platform_security'],
        'maintenance' => ['label' => 'Maintenance', 'route_group' => 'system_maintenance'],
    ],

    'modes' => [
        DeploymentModeService::MODE_SAAS => [
            'label' => 'SaaS Platform',
            'description' => 'Central Sanfaani-hosted multi-school platform.',
            'commercial_model_label' => 'Subscription SaaS',
            'route_groups' => [
                'platform_dashboard',
                'platform_schools',
                'platform_onboarding',
                'platform_subscriptions',
                'platform_features',
                'platform_marketing',
                'platform_demo',
                'demo_sessions',
                'guided_onboarding',
                'platform_payments',
                'platform_result_system',
                'platform_scratch_cards',
                'platform_communications',
                'platform_support',
                'platform_mail',
                'platform_settings',
                'platform_security',
                'platform_audit',
                'system_maintenance',
                'system_status',
            ],
            'hidden_route_groups' => [
                'standalone_installer',
                'standalone_license',
                'standalone_updates',
                'managed_backups',
                'managed_updates',
                'managed_white_label',
            ],
            'dashboard_widgets' => [
                'schools_total',
                'active_subscriptions',
                'demo_requests',
                'lead_pipeline',
                'scratch_card_requests',
                'platform_payments',
                'system_health',
                'onboarding_progress',
                'marketing_new_leads',
                'marketing_sales_tasks',
                'marketing_trial_leads',
                'marketing_renewals',
                'marketing_conversions',
            ],
            'settings_sections' => [
                'platform',
                'billing',
                'marketing',
                'localization',
                'security',
                'maintenance',
            ],
            'allowed_admin_sections' => [
                'platform',
                'operations',
                'email_marketing',
                'governance',
            ],
        ],

        DeploymentModeService::MODE_SINGLE_SCHOOL => [
            'label' => 'Single-School Installation',
            'description' => 'Licensed installation for one school with local owner administration.',
            'commercial_model_label' => 'Standalone License',
            'route_groups' => [
                'local_dashboard',
                'local_school_settings',
                'local_branding',
                'local_mail_settings',
                'license_activation',
                'standalone_installer',
                'standalone_license',
                'standalone_updates',
                'demo_sessions',
                'guided_onboarding',
                'platform_security',
                'platform_audit',
                'system_maintenance',
                'system_status',
            ],
            'hidden_route_groups' => [
                'platform_schools',
                'platform_onboarding',
                'platform_subscriptions',
                'platform_marketing',
                'platform_demo',
                'platform_payments',
                'managed_backups',
                'managed_updates',
                'managed_support',
                'managed_white_label',
            ],
            'dashboard_widgets' => [
                'local_school_profile',
                'local_license_status',
                'local_update_status',
                'system_health',
                'onboarding_progress',
            ],
            'settings_sections' => [
                'local_school',
                'local_branding',
                'local_mail',
                'license',
                'updates',
                'security',
                'maintenance',
            ],
            'allowed_admin_sections' => [
                'local',
                'standalone',
                'governance',
            ],
        ],

        DeploymentModeService::MODE_MANAGED => [
            'label' => 'Managed Client Deployment',
            'description' => 'Sanfaani-operated deployment configured through flags and mode policy.',
            'commercial_model_label' => 'Managed Contract',
            'route_groups' => [
                'platform_dashboard',
                'platform_schools',
                'platform_result_system',
                'platform_scratch_cards',
                'platform_communications',
                'platform_support',
                'platform_marketing',
                'demo_sessions',
                'guided_onboarding',
                'platform_mail',
                'platform_settings',
                'platform_security',
                'platform_audit',
                'managed_support',
                'managed_backups',
                'managed_updates',
                'managed_white_label',
                'license_activation',
                'standalone_installer',
                'system_maintenance',
                'system_status',
            ],
            'hidden_route_groups' => [
                'platform_onboarding',
                'platform_subscriptions',
                'platform_demo',
                'standalone_license',
            ],
            'dashboard_widgets' => [
                'schools_total',
                'scratch_card_requests',
                'managed_support_status',
                'managed_backup_status',
                'managed_update_status',
                'white_label_status',
                'system_health',
                'onboarding_progress',
                'marketing_new_leads',
                'marketing_sales_tasks',
                'marketing_renewals',
                'marketing_conversions',
            ],
            'settings_sections' => [
                'platform',
                'managed_support',
                'managed_backups',
                'managed_updates',
                'white_label',
                'security',
                'maintenance',
            ],
            'allowed_admin_sections' => [
                'platform',
                'managed',
                'governance',
            ],
        ],
    ],
];
