<?php

use App\Services\System\DeploymentModeService;

/*
|--------------------------------------------------------------------------
| Sanfaani Feature Catalog
|--------------------------------------------------------------------------
|
| This catalog is the global source of truth for module-level feature gates.
| It does not create billing, licensing, installer, demo, update, or backup
| behavior. It only describes when those future modules may be exposed.
|
| School-specific decisions continue to use existing SchoolFeatureOverride,
| SchoolSubscription, and PlanFeature records. The optional entitlement_keys
| entries below map module-level flags to existing plan/override keys.
|
*/

$allDeploymentModes = DeploymentModeService::DEPLOYMENT_MODES;
$allLicenseModes = DeploymentModeService::LICENSE_MODES;

return [
    'features' => [
        'saas_billing' => [
            'enabled' => true,
            'category' => 'commercial',
            'deployment_modes' => [DeploymentModeService::MODE_SAAS],
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Centralized SaaS billing and subscription management.',
        ],
        'standalone_installer' => [
            'enabled' => true,
            'category' => 'deployment',
            'deployment_modes' => [
                DeploymentModeService::MODE_SINGLE_SCHOOL,
                DeploymentModeService::MODE_MANAGED,
            ],
            'license_modes' => [
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Guided setup gates for standalone licensed deployments.',
        ],
        'license_activation' => [
            'enabled' => true,
            'category' => 'commercial',
            'deployment_modes' => [
                DeploymentModeService::MODE_SINGLE_SCHOOL,
                DeploymentModeService::MODE_MANAGED,
            ],
            'license_modes' => [
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'License activation gates for non-SaaS installations.',
        ],
        'demo_system' => [
            'enabled' => true,
            'category' => 'commercial',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Demo-mode controls for safe evaluation environments.',
        ],
        'guided_onboarding' => [
            'enabled' => true,
            'category' => 'experience',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Role-based onboarding checklists, progress widgets, and guided setup visibility.',
        ],
        'update_manager' => [
            'enabled' => (bool) env('SANFAANI_UPDATES_ENABLED', true),
            'category' => 'operations',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['update_manager', 'updates', 'guided_updates'],
            'description' => 'Guided update package review, preflight, entitlement, and rollback planning gate.',
        ],
        'backup_manager' => [
            'enabled' => (bool) env('SANFAANI_BACKUPS_ENABLED', true),
            'category' => 'operations',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['backup_manager', 'backups', 'managed_backups'],
            'description' => 'Backup metadata, verification, retention, restore planning, and pre-update readiness gate.',
        ],
        'managed_backups' => [
            'enabled' => (bool) env('SANFAANI_BACKUPS_ENABLED', true),
            'category' => 'operations',
            'deployment_modes' => [DeploymentModeService::MODE_MANAGED],
            'license_modes' => [DeploymentModeService::LICENSE_MANAGED_CONTRACT],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['managed_backups', 'backup_manager', 'backups'],
            'description' => 'Managed backup tooling for contracted deployments.',
        ],
        'performance_diagnostics' => [
            'enabled' => (bool) env('SANFAANI_PERFORMANCE_DIAGNOSTICS_ENABLED', true),
            'category' => 'operations',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Read-only hosting, cache, queue, log, asset, and query readiness diagnostics.',
        ],
        'security_diagnostics' => [
            'enabled' => (bool) env('SANFAANI_SECURITY_DIAGNOSTICS_ENABLED', true),
            'category' => 'operations',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Read-only outbound email, logging, token, and production security diagnostics.',
        ],
        'white_label_branding' => [
            'enabled' => true,
            'category' => 'branding',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['website_customization'],
            'description' => 'School-specific white-label identity and public branding.',
        ],
        'marketing_automation' => [
            'enabled' => true,
            'category' => 'growth',
            'deployment_modes' => [
                DeploymentModeService::MODE_SAAS,
                DeploymentModeService::MODE_MANAGED,
            ],
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Lead nurturing, campaigns, and marketing automation.',
        ],
        'scratch_cards' => [
            'enabled' => true,
            'category' => 'results',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['scratch_cards'],
            'authorization_features' => ['scratch_cards.manage'],
            'description' => 'Scratch-card result access requests, generation, and usage.',
        ],
        'parent_portal' => [
            'enabled' => false,
            'category' => 'portal',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Parent portal visibility gate for future portal work.',
        ],
        'student_portal' => [
            'enabled' => false,
            'category' => 'portal',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'Student portal visibility gate for future portal work.',
        ],
        'cbt' => [
            'enabled' => true,
            'category' => 'academics',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['cbt_exams', 'cbt_question_bank', 'cbt_results'],
            'authorization_features' => ['cbt.manage', 'cbt.question_bank', 'cbt.publish_results'],
            'description' => 'Computer-based testing modules and result integration.',
        ],
        'advanced_reports' => [
            'enabled' => true,
            'category' => 'reports',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_ANNUAL,
                DeploymentModeService::LICENSE_LIFETIME,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
                DeploymentModeService::LICENSE_TRIAL,
                DeploymentModeService::LICENSE_DEMO,
            ],
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['report_card_customization', 'report_card_templates', 'pdf_snapshots'],
            'description' => 'Advanced report-card templates, exports, and analytics gates.',
        ],
        'api_access' => [
            'enabled' => false,
            'category' => 'integration',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => [
                DeploymentModeService::LICENSE_SUBSCRIPTION,
                DeploymentModeService::LICENSE_MANAGED_CONTRACT,
                DeploymentModeService::LICENSE_WHITE_LABEL,
            ],
            'requires_school' => false,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'description' => 'External API access gate for future integrations.',
        ],
        'public_school_pages' => [
            'enabled' => true,
            'category' => 'public',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['website_customization'],
            'description' => 'Public school profile pages and admissions visibility.',
        ],
        'result_publication' => [
            'enabled' => true,
            'category' => 'results',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['result_publishing'],
            'authorization_features' => ['results.publish'],
            'description' => 'Result publishing workflow and public result availability.',
        ],
        'communication_tools' => [
            'enabled' => true,
            'category' => 'communication',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'authorization_features' => ['communication.send', 'communication.bulk'],
            'description' => 'School communication center and bulk messaging gates.',
        ],
        'support_tools' => [
            'enabled' => true,
            'category' => 'support',
            'deployment_modes' => $allDeploymentModes,
            'license_modes' => $allLicenseModes,
            'requires_school' => true,
            'super_admin_bypass' => true,
            'hidden_when_disabled' => true,
            'entitlement_keys' => ['support.access'],
            'authorization_features' => ['support.manage'],
            'description' => 'School support threads, escalation, and managed support gates.',
        ],
    ],
];
