<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Marketplace Packaging Foundation
    |--------------------------------------------------------------------------
    |
    | This manifest describes what a future marketplace package should contain
    | and what must stay out. The validator reads this list only; it does not
    | build, copy, zip, upload, or delete files.
    |
    */

    'package_name' => 'sanfaani-schools',

    'default_channel' => 'stable',

    'package_modes' => [
        'marketplace_single_school',
        'direct_single_school',
        'managed_client',
        'white_label',
        'demo_sales',
    ],

    'output_path' => 'storage/app/marketplace-packages',

    'builder_root' => null,

    'include_paths' => [
        'app',
        'bootstrap',
        'config',
        'database',
        'docs',
        'lang',
        'public',
        'resources',
        'routes',
        'tests',
        'artisan',
        'composer.json',
        'composer.lock',
        'package.json',
        'package-lock.json',
        'postcss.config.js',
        'tailwind.config.js',
        'vite.config.js',
        'phpunit.xml',
        '.env.example',
        '.env.marketplace.example',
        'CHANGELOG.md',
        'DEPLOYMENT.md',
        'README.md',
    ],

    'exclude_paths' => [
        '.git',
        '.env',
        '.env.backup',
        '.env.production',
        '.env.*.local',
        'vendor',
        'node_modules',
        'storage/logs',
        'storage/framework/cache',
        'storage/framework/sessions',
        'storage/framework/views',
        'storage/app/backups',
        'storage/app/private',
        'storage/app/database',
        'storage/app/updates',
        'storage/app/marketplace-packages',
        'backups',
        'public/build.zip',
        'database/*.sqlite',
        'database/*.sqlite-*',
        '.idea',
        '.vscode',
        '.DS_Store',
        'Thumbs.db',
        '*.key',
        '*.pem',
        '*.p12',
        '*.dump',
        '*.sql',
        '*.tar',
        '*.tar.gz',
        '*.zip',
        'coverage',
        '.phpunit.cache',
        'npm-debug.log',
        'yarn-error.log',
    ],

    'prohibited_paths' => [
        '.git',
        '.env',
        'node_modules',
        'storage/logs',
        'storage/framework/cache',
        'storage/framework/sessions',
        'storage/framework/views',
        'storage/app/backups',
        'storage/app/private',
        'storage/app/marketplace-packages',
        'backups',
        'public/build.zip',
    ],

    'package_profiles' => [
        'technical' => [
            'description' => 'Source package for technical buyers who will install dependencies and build assets themselves.',
            'include_paths' => [
                'app',
                'bootstrap',
                'config',
                'database',
                'docs',
                'lang',
                'public',
                'resources',
                'routes',
                'tests',
                'artisan',
                'composer.json',
                'composer.lock',
                'package.json',
                'package-lock.json',
                'postcss.config.js',
                'tailwind.config.js',
                'vite.config.js',
                'phpunit.xml',
                '.env.example',
                '.env.marketplace.example',
                'CHANGELOG.md',
                'DEPLOYMENT.md',
                'README.md',
            ],
            'exclude_paths' => [
                '.git',
                '.env',
                '.env.backup',
                '.env.production',
                '.env.*.local',
                'vendor',
                'node_modules',
                'public/build',
                'public/build.zip',
                'storage/logs',
                'storage/framework/cache',
                'storage/framework/sessions',
                'storage/framework/views',
                'storage/app/backups',
                'storage/app/private',
                'storage/app/database',
                'storage/app/updates',
                'storage/app/marketplace-packages',
                'backups',
                'database/*.sqlite',
                'database/*.sqlite-*',
                '.idea',
                '.vscode',
                '.DS_Store',
                'Thumbs.db',
                '*.key',
                '*.pem',
                '*.p12',
                '*.dump',
                '*.sql',
                '*.tar',
                '*.tar.gz',
                '*.zip',
                'coverage',
                '.phpunit.cache',
                '.phpunit.result.cache',
                'npm-debug.log',
                'yarn-error.log',
            ],
        ],

        'cpanel_ready' => [
            'description' => 'Shared-hosting package for buyers who need committed PHP dependencies and built frontend assets.',
            'include_paths' => [
                'app',
                'bootstrap',
                'config',
                'database',
                'docs',
                'lang',
                'public',
                'public/build',
                'resources',
                'routes',
                'tests',
                'vendor',
                'artisan',
                'composer.json',
                'composer.lock',
                'package.json',
                'package-lock.json',
                'postcss.config.js',
                'tailwind.config.js',
                'vite.config.js',
                'phpunit.xml',
                '.env.example',
                '.env.marketplace.example',
                'CHANGELOG.md',
                'DEPLOYMENT.md',
                'README.md',
            ],
            'exclude_paths' => [
                '.git',
                '.env',
                '.env.backup',
                '.env.production',
                '.env.*.local',
                'node_modules',
                'public/build.zip',
                'storage/logs',
                'storage/framework/cache',
                'storage/framework/sessions',
                'storage/framework/views',
                'storage/app/backups',
                'storage/app/private',
                'storage/app/database',
                'storage/app/updates',
                'storage/app/marketplace-packages',
                'backups',
                'database/*.sqlite',
                'database/*.sqlite-*',
                '.idea',
                '.vscode',
                '.DS_Store',
                'Thumbs.db',
                '*.key',
                '*.pem',
                '*.p12',
                '*.dump',
                '*.sql',
                '*.tar',
                '*.tar.gz',
                '*.zip',
                'coverage',
                '.phpunit.cache',
                '.phpunit.result.cache',
                'npm-debug.log',
                'yarn-error.log',
            ],
            'warnings' => [
                'public/build/manifest.json' => 'public/build/manifest.json is missing; run npm run build before releasing cpanel_ready packages.',
                'vendor' => 'vendor/ is missing; run composer install --no-dev before releasing cpanel_ready packages.',
            ],
        ],

        'managed_handover' => [
            'description' => 'Documentation and checklist handover package for Sanfaani team/client managed installations.',
            'include_paths' => [
                'docs',
                '.env.marketplace.example',
                'README.md',
                'DEPLOYMENT.md',
            ],
            'exclude_paths' => [
                '.git',
                '.env',
                '.env.backup',
                '.env.production',
                '.env.*.local',
                'vendor',
                'node_modules',
                'public/build.zip',
                'storage/logs',
                'storage/framework/cache',
                'storage/framework/sessions',
                'storage/framework/views',
                'storage/app/backups',
                'storage/app/private',
                'storage/app/database',
                'storage/app/updates',
                'storage/app/marketplace-packages',
                'backups',
                'database/*.sqlite',
                'database/*.sqlite-*',
                '.idea',
                '.vscode',
                '.DS_Store',
                'Thumbs.db',
                '*.key',
                '*.pem',
                '*.p12',
                '*.dump',
                '*.sql',
                '*.tar',
                '*.tar.gz',
                '*.zip',
                'coverage',
                '.phpunit.cache',
                '.phpunit.result.cache',
                'npm-debug.log',
                'yarn-error.log',
            ],
        ],
    ],

    'required_docs' => [
        'docs/marketplace/marketplace-package-structure.md',
        'docs/marketplace/include-exclude-list.md',
        'docs/marketplace/buyer-installation-checklist.md',
        'docs/marketplace/marketplace-documentation-checklist.md',
        'docs/marketplace/screenshot-checklist.md',
        'docs/marketplace/demo-checklist.md',
        'docs/marketplace/reseller-checklist.md',
        'docs/marketplace/release-packaging-checklist.md',
        'docs/marketplace/package-validation-checklist.md',
        'docs/marketplace/post-purchase-onboarding-checklist.md',
        'docs/marketplace/white-label-buyer-checklist.md',
        'docs/marketplace/managed-client-handover-checklist.md',
        'docs/marketplace/marketplace-listing-copy.md',
        'docs/marketplace/marketplace-packaging-plan.md',
        'docs/marketplace/standalone-package-builder.md',
        'docs/marketplace/standalone-package-qa-checklist.md',
        'docs/marketplace/cpanel-ready-package-guide.md',
        'docs/marketplace/cpanel-ready-package-acceptance-test.md',
        'docs/marketplace/technical-buyer-package-guide.md',
        'docs/marketplace/done-for-you-installation-offer.md',
        'docs/installation/single-school-installer.md',
        'docs/installation/standalone-buyer-installation-flow.md',
        'docs/installation/standalone-installer-acceptance-test.md',
        'docs/support/standalone-buyer-support-playbook.md',
        'docs/licensing/license-activation.md',
        'docs/updates/update-system-plan.md',
        'docs/backups/backup-system-plan.md',
    ],

    'required_checks' => [
        'required_docs_exist',
        'marketplace_env_template_safe',
        'prohibited_paths_excluded',
        'public_build_zip_excluded',
        'installer_license_update_backup_docs_present',
    ],

    'marketplace_assets' => [
        'listing_copy' => 'docs/marketplace/marketplace-listing-copy.md',
        'screenshots' => 'docs/marketplace/screenshot-checklist.md',
        'demo_script' => 'docs/marketplace/demo-checklist.md',
        'buyer_docs' => 'docs/marketplace/buyer-installation-checklist.md',
    ],
];
