<?php

return [
    'deployment' => [
        'mode' => env('SANFAANI_DEPLOYMENT_MODE', 'saas'),
        'license_mode' => env('SANFAANI_LICENSE_MODE', 'subscription'),
        'brand_mode' => env('SANFAANI_BRAND_MODE', 'default'),
        'updates_enabled' => (bool) env('SANFAANI_UPDATES_ENABLED', true),
        'demo_enabled' => (bool) env('SANFAANI_DEMO_ENABLED', false),
    ],
    'platform_name' => env('SANFAANI_PLATFORM_NAME', 'Sanfaani Schools'),
    'company_name' => env('SANFAANI_COMPANY_NAME', 'Sanfaani Ltd'),
    'product_url' => env('SANFAANI_PRODUCT_URL', 'https://schools.sanfaani.net'),
    'main_company_url' => env('SANFAANI_MAIN_URL', 'https://sanfaani.net'),
    'support_email' => env('SANFAANI_SUPPORT_EMAIL', 'Sanfaanischools@gmail.com'),
    'sales_email' => env('SANFAANI_SALES_EMAIL', env('SANFAANI_SUPPORT_EMAIL', 'sanfaanisaas@gmail.com')),
    'support_phone' => env('SANFAANI_SUPPORT_PHONE', '+2349010172138'),
    'support_whatsapp' => env('SANFAANI_SUPPORT_WHATSAPP', env('SANFAANI_WHATSAPP_NUMBER', '+2349010172138')),
    'whatsapp_number' => env('SANFAANI_WHATSAPP_NUMBER', env('SANFAANI_SUPPORT_WHATSAPP', '+2349010172138')),
    'address' => env('SANFAANI_ADDRESS', env('SANFAANI_BUSINESS_ADDRESS')),
    'business_address' => env('SANFAANI_BUSINESS_ADDRESS', env('SANFAANI_ADDRESS')),
    'website_url' => env('SANFAANI_WEBSITE_URL'),
    'official_email' => env('SANFAANI_OFFICIAL_EMAIL', env('SANFAANI_SUPPORT_EMAIL', 'sanfaanisaas@gmail.com')),
    'timezone' => env('SANFAANI_TIMEZONE', env('APP_TIMEZONE', 'UTC')),
    'default_country' => env('SANFAANI_DEFAULT_COUNTRY', 'Nigeria'),
    'default_currency' => env('SANFAANI_DEFAULT_CURRENCY', 'NGN'),
    'default_language' => env('SANFAANI_DEFAULT_LANGUAGE', 'en'),
    'supported_languages' => array_filter(array_map('trim', explode(',', env('SANFAANI_SUPPORTED_LANGUAGES', 'en,ar,fr')))),
    'languages' => [
        'en' => ['label' => 'English', 'native' => 'English', 'short' => 'EN', 'rtl' => false],
        'ar' => ['label' => 'Arabic', 'native' => 'العربية', 'short' => 'AR', 'rtl' => true],
        'fr' => ['label' => 'French', 'native' => 'Français', 'short' => 'FR', 'rtl' => false],
        'yo' => ['label' => 'Yoruba', 'native' => 'Yoruba', 'short' => 'YO', 'rtl' => false],
        'ha' => ['label' => 'Hausa', 'native' => 'Hausa', 'short' => 'HA', 'rtl' => false],
    ],
    'rtl_locales' => ['ar'],
    'marketing' => [
        'queue' => env('SANFAANI_MARKETING_QUEUE', 'marketing'),
        'chunk_size' => (int) env('SANFAANI_MARKETING_CHUNK_SIZE', 100),
        'dispatch_delay_seconds' => (int) env('SANFAANI_MARKETING_DISPATCH_DELAY_SECONDS', 2),
        'max_retry_attempts' => (int) env('SANFAANI_MARKETING_MAX_RETRY_ATTEMPTS', 3),
        'tracking_url_ttl_days' => (int) env('SANFAANI_MARKETING_TRACKING_URL_TTL_DAYS', 30),
        'allow_destructive_rollbacks' => (bool) env('SANFAANI_MARKETING_ALLOW_DESTRUCTIVE_ROLLBACKS', false),
    ],
    'cbt' => [
        'autosave_seconds' => (int) env('SANFAANI_CBT_AUTOSAVE_SECONDS', 20),
        'candidate_code_ttl_days' => (int) env('SANFAANI_CBT_CODE_TTL_DAYS', 30),
        'question_import_chunk_size' => (int) env('SANFAANI_CBT_IMPORT_CHUNK_SIZE', 250),
        'public_throttle' => env('SANFAANI_CBT_PUBLIC_THROTTLE', '12,1'),
    ],
    'pdf' => [
        'disk' => env('SANFAANI_PDF_DISK', 'local'),
        'watermark_enabled' => (bool) env('SANFAANI_PDF_WATERMARK_ENABLED', true),
        'queue' => env('SANFAANI_PDF_QUEUE', 'default'),
    ],
    'idle_timeout_minutes' => (int) env('SANFAANI_IDLE_TIMEOUT_MINUTES', 30),
    'backups' => [
        'retention_count' => (int) env('SANFAANI_BACKUP_RETENTION_COUNT', 10),
        'chunk_size' => (int) env('SANFAANI_BACKUP_CHUNK_SIZE', 500),
    ],
];
