<div class="space-y-6">
    <h2 class="sr-only">Accountant Dashboard</h2>

    <section class="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]">
        <x-ui.panel>
            <p class="text-xs font-semibold uppercase tracking-normal text-brand-primary">Fees and accounting foundation</p>
            <h3 class="mt-2 text-2xl font-semibold text-text-primary">{{ $school->name }}</h3>
            <p class="mt-2 text-sm leading-6 text-text-secondary">
                Online fee setup, student invoices, manual payment recording, finance reports, and audit review are available. Import/export remains Stage 12; gateways and offline fee capture are deferred.
            </p>
            <div class="mt-4 flex flex-wrap gap-2">
                <a href="{{ route('school.finance.index') }}" class="ui-button-primary">Open Finance</a>
                <a href="{{ route('school.finance.reports') }}" class="ui-button-secondary">Reports</a>
                <a href="{{ route('school.finance.audit') }}" class="ui-button-secondary">Audit Review</a>
                <a href="{{ route('school.finance.invoices.index') }}" class="ui-button-secondary">View Invoices</a>
            </div>
        </x-ui.panel>

        <x-ui.panel>
            <p class="text-xs font-semibold uppercase tracking-normal text-text-tertiary">Outstanding balance</p>
            <p class="mt-2 text-3xl font-semibold text-text-primary">NGN {{ number_format($financeSummary['total_balance'] ?? 0, 2) }}</p>
            <p class="mt-2 text-sm text-text-secondary">{{ $financeSummary['outstanding_invoices'] ?? 0 }} invoice(s) still have a balance.</p>
        </x-ui.panel>
    </section>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <x-ui.stat-card label="Billed" :value="'NGN ' . number_format($financeSummary['total_billed'] ?? 0, 2)" :meta="'Discount: NGN ' . number_format($financeSummary['total_discount'] ?? 0, 2)" />
        <x-ui.stat-card label="Paid" :value="'NGN ' . number_format($financeSummary['total_paid'] ?? 0, 2)" :meta="($financeSummary['payments'] ?? 0) . ' payment(s)'" tone="success" />
        <x-ui.stat-card label="Outstanding" :value="'NGN ' . number_format($financeSummary['total_balance'] ?? 0, 2)" :meta="($financeSummary['outstanding_invoices'] ?? 0) . ' invoice(s)'" tone="warning" />
        <x-ui.stat-card label="Fee Items" :value="$financeSummary['fee_items'] ?? 0" :meta="($financeSummary['active_fee_items'] ?? 0) . ' active'" />
        <x-ui.stat-card label="Assignments" :value="$financeSummary['assignments'] ?? 0" :meta="($financeSummary['active_assignments'] ?? 0) . ' active'" />
        <x-ui.stat-card label="Invoices" :value="$financeSummary['invoices'] ?? 0" :meta="($financeSummary['part_paid_invoices'] ?? 0) . ' part paid'" tone="info" />
    </section>

    <section class="grid gap-4 lg:grid-cols-2">
        <x-ui.panel>
            <div class="flex items-center justify-between gap-3">
                <div>
                    <h3 class="text-base font-semibold text-text-primary">Recent Invoices</h3>
                    <p class="mt-1 text-sm text-text-secondary">Latest student bills generated by school finance.</p>
                </div>
                <a href="{{ route('school.finance.invoices.index') }}" class="ui-button-secondary">Open</a>
            </div>
            <div class="mt-4 space-y-3">
                @forelse ($recentInvoices as $invoice)
                    <a href="{{ route('school.finance.invoices.show', $invoice) }}" class="block rounded-md border border-border-subtle bg-bg-primary p-3 text-sm hover:bg-bg-tertiary">
                        <span class="font-semibold text-text-primary">{{ $invoice->invoice_number }}</span>
                        <span class="ms-2 text-text-secondary">{{ $invoice->student?->fullName() ?? 'Student' }}</span>
                        <span class="float-right font-mono text-brand-primary">NGN {{ number_format($invoice->balance_amount, 2) }}</span>
                    </a>
                @empty
                    <p class="rounded-md border border-border-subtle bg-bg-primary p-3 text-sm text-text-secondary">No fee invoices have been generated yet.</p>
                @endforelse
            </div>
        </x-ui.panel>

        <x-ui.panel>
            <div class="flex items-center justify-between gap-3">
                <div>
                    <h3 class="text-base font-semibold text-text-primary">Recent Payments</h3>
                    <p class="mt-1 text-sm text-text-secondary">Manual payment receipts recorded online.</p>
                </div>
                <a href="{{ route('school.finance.invoices.index') }}" class="ui-button-secondary">Record Payment</a>
            </div>
            <div class="mt-4 space-y-3">
                @forelse ($recentPayments as $payment)
                    <div class="rounded-md border border-border-subtle bg-bg-primary p-3 text-sm">
                        <span class="font-semibold text-text-primary">NGN {{ number_format($payment->amount, 2) }}</span>
                        <span class="ms-2 text-text-secondary">{{ $payment->student?->fullName() ?? 'Student' }}</span>
                        <span class="float-right text-text-tertiary">{{ $payment->payment_date?->format('d M Y') }}</span>
                    </div>
                @empty
                    <p class="rounded-md border border-border-subtle bg-bg-primary p-3 text-sm text-text-secondary">No payments have been recorded yet.</p>
                @endforelse
            </div>
        </x-ui.panel>
    </section>
</div>
